server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: utilisateurs
#  datasource:
#    url: jdbc:postgresql://localhost:5432/utilisateurs
#    username: postgres
#    password: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app:
  keycloak:
    realm: ${APP_KEYCLOAK_REALM}
    serverUrl: ${APP_KEYCLOAK_SERVER_URL}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    admin-username: admin
    admin-password: admin


management:
  tracing:
    sampling:
      probability: 1.0