version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: utilisateurs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres
  config-server:
    build: ./config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
    ports:
      - "8888:8888"
    volumes:
      - ./config/config-server.yml:/config/config-server.yml
    command: ["java", "-jar", "/app/config-server.jar", "--spring.config.location=classpath:/config/config-server.yml"]

  discovery-server:
    build: ./discovery-server
    environment:
      EUREKA_INSTANCE_HOSTNAME: discovery-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
      EUREKA_CLIENT_FETCH_REGISTRY: 'false'
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    volumes:
      - ./config/discovery-server.yml:/config/discovery-server.yml
    command: ["java", "-jar", "/app/discovery-server.jar", "--spring.config.location=classpath:/config/discovery-server.yml"]

  gateway:
    build: ./gateway
    environment:
      SPRING_APPLICATION_NAME: gateway
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: 'true'
    ports:
      - "8222:8222"
    depends_on:
      - discovery-server
      - utilisateurs
    volumes:
      - ./config/gateway.yml:/config/gateway.yml
    command: ["java", "-jar", "/app/gateway.jar", "--spring.config.location=classpath:/config/gateway.yml"]

  utilisateurs:
    build: ./utilisateur
    environment:
      SPRING_APPLICATION_NAME: utilisateur
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/utilisateurs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8070:8070"
    depends_on:
      - postgres
      - discovery-server
      - config-server
    volumes:
      - ./config/utilisateurs.yml:/config/utilisateurs.yml
    command: ["java", "-jar", "/app/utilisateur.jar", "--spring.config.location=classpath:/config/utilisateurs.yml"]

  laboratoires:
    build: ./laboratoire
    environment:
      SPRING_APPLICATION_NAME: laboratoire
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/laboratoires
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - discovery-server
      - config-server
    volumes:
      - ./config/laboratoires.yml:/config/laboratoires.yml
    command: ["java", "-jar", "/app/laboratoire.jar", "--spring.config.location=classpath:/config/laboratoires.yml"]


volumes:
  postgres_data:
    driver: local
