services:
  # PostgreSQL Database for Utilisateur Service
  utilisateurs-db:
    image: postgres:latest
    container_name: utilisateurs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: utilisateurs
      PGDATA: /data/users
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./users_data:/data/users

  # PostgreSQL Database for Laboratoire Service
  laboratoires-db:
    image: postgres:latest
    container_name: laboratoires-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laboratories
      PGDATA: /data/labos
      POSTGRES_HOST_AUTH_METHOD: trust
      PGPORT: "5433"
    ports:
      - "5433:5433"
    networks:
      - app-network
    volumes:
      - ./labos_data:/data/labos

  # PostgreSQL Database for Laboratoire Service
  patients-db:
    image: postgres:latest
    container_name: patients-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients
      PGDATA: /data/patient
      POSTGRES_HOST_AUTH_METHOD: trust
      PGPORT: "5434"
    ports:
      - "5434:5434"
    networks:
      - app-network
    volumes:
      - ./patient_data:/data/patient


  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - app-network

  utilisateurs:
    build:
      context: ./utilisateur
      dockerfile: Dockerfile
    container_name: utilisateurs
    ports:
      - "8070:8070"
    depends_on:
      - utilisateurs-db
      - discovery-server
    networks:
      - app-network

  laboratoires:
    build:
      context: ./laboratoire
      dockerfile: Dockerfile
    container_name: laboratoires
    ports:
      - "8090:8090"
    depends_on:
      - laboratoires-db
      - discovery-server
    networks:
      - app-network

  patients:
    build:
      context: ./patient
      dockerfile: Dockerfile
    container_name: patients
    ports:
      - "8090:8090"
    depends_on:
      - patients-db
      - discovery-server
    networks:
      - app-network
# Define the network
networks:
  app-network:
    driver: bridge
# Define the volumes
volumes:
  users_data:
  labos_data:
  patient_data:

