server:
  port: 8072
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: patients
  datasource:
    url: jdbc:postgresql://localhost:5434/patients
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app:
  keycloak:
    realm: ${APP_KEYCLOAK_REALM}
    serverUrl: ${APP_KEYCLOAK_SERVER_URL}

application:
  config:
    patients-url: http://localhost:8080/api/v1/patients

management:
  tracing:
    sampling:
      probability: 1.0