server:
  port: 8072
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka


spring:
  application:
    name: patients
  datasource:
    url: jdbc:postgresql://patients-db:5434/patients
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    patients-url: http://gateway:8080/api/v1/patients

management:
  tracing:
    sampling:
      probability: 1.0