server:
  port: 8073
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: analyses
  datasource:
    url: jdbc:postgresql://localhost:5435/analyses
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app:
  keycloak:
    realm: ${APP_KEYCLOAK_REALM}
    serverUrl: ${APP_KEYCLOAK_SERVER_URL}

management:
  tracing:
    sampling:
      probability: 1.0