server:
  port: 8073
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: analyses
  datasource:
    url: jdbc:postgresql://localhost:5435/analyses
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    analyses-url: http://localhost:8080/api/v1/analyse

management:
  tracing:
    sampling:
      probability: 1.0