server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: utilisateurs
          uri: lb://utilisateurs
          predicates:
            - Path=/api/v1/utilisateurs/**

        - id: laboratoires
          uri: lb://laboratoires
          predicates:
            - Path=/api/v1/laboratoires/**
            - Path=/api/v1/contacts/**
            - Path=/api/v1/adresses/**

        - id: patients
          uri: lb://patients
          predicates:
            - Path=/api/v1/patients/**
            - Path=/api/v1/dossiers/**

        - id: analyses
          uri: lb://analyses
          predicates:
            - Path=/api/v1/analyses/**
            - Path=/api/v1/epreuves/**

        - id: examins
          uri: lb://examins
          predicates:
            - Path=/api/v1/examens/**

        - id: tests
          uri: lb://tests
          predicates:
            - Path=/api/v1/tests/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://localhost:8090/realms/labo-realm"
#          jwk-set-uri: "http://localhost:8090/realms/labo-realm/protocol/openid-connect/certs"
