server:
  port: 8074
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: examins
  datasource:
    url: jdbc:postgresql://localhost:5436/examins
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    examins-url: http://localhost:8080/api/v1/examins

management:
  tracing:
    sampling:
      probability: 1.0