eureka:
  client:
    service-url:
      register.with.eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: utilisateurs
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/utilisateurs/**
# here to add routes of other microserv