# laboratoire.yml
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: laboratoires
  datasource:
    url: jdbc:postgresql://localhost:5432/laboratoires
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    laboratoire-url: http://localhost:8222/api/v1/laboratoires