server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: utilisateurs
  datasource:
    url: jdbc:postgresql://localhost:5432/utilisateurs
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    utilisateurs-url: http://localhost:8080/api/v1/utilisateurs

management:
  tracing:
    sampling:
      probability: 1.0