server:
  port: 8071
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: laboratoires
  datasource:
    url: jdbc:postgresql://localhost:5433/laboratories
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  config:
    laboratoires-url: http://localhost:8080/api/v1/laboratoires

management:
  tracing:
    sampling:
      probability: 1.0